name: Build Image & Release

on:
  push:
    tags: ['*']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make-release:
    name: Make Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: .github/changelog-builder.json
          ignorePreReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo '${{ steps.changelog.outputs.changelog }}' > changelog.md

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: |
            changelog.md

      - name: Make Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            ${{ steps.changelog.outputs.changelog }}
          allowUpdates: true
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') || contains(github.ref, 'pre') }}
          draft: true
